version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: eduflow_api
    restart: always
    ports:
      - "3005:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://173.212.195.88:3006
      - API_URL=http://173.212.195.88:3005
      - CORS_ORIGIN=http://173.212.195.88:3006,http://localhost:3000,http://localhost:3006
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_USE_SSL=false
      - MINIO_PUBLIC_ENDPOINT=http://173.212.195.88:9007
    depends_on:
      - postgres
      - redis
      - minio

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ""
        API_URL: http://api:3001
    container_name: eduflow_web
    restart: always
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=
      - API_URL=http://api:3001
    depends_on:
      - api

  postgres:
    image: postgres:16-alpine
    container_name: eduflow_prod_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: eduflow_prod_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data_prod:/data

  minio:
    image: minio/minio:latest
    container_name: eduflow_prod_minio
    restart: always
    ports:
      - "9007:9000"
      - "9008:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_prod:/data

volumes:
  postgres_data_prod:
  redis_data_prod:
  minio_data_prod:
